# Generated by Django 3.1 on 2020-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0005_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
    ]
